#pragma once

#define ERR_MSG_GET_CLIENT_RECT "'GetClientRect' Failed!"
#define ERR_MSG_BEGIN_PAINT "No Display Device Context is Available!"
#define ERR_MSG_FILL_RECT "'FillRect' Failed!"
#define ERR_MSG_GET_DC "'GetDC' Failed!"
#define ERR_MSG_SET_BK_MODE "'SEtBkMode' Failed!"
#define ERR_MSG_RELEASE_DC "The Specified DC Was not Released!"
#define ERR_MSG_SET_WINDOW_POS "'SetWindowPos' Failed!"
#define ERR_MSG_TEXT_OUT "'TextOut' Failed!"
#define ERR_MSG_INVALIDATE_RECT "'InvalidateRect' Failed!"
#define ERR_MSG_CREATE_FONT "'CreateFont' Failed!"
#define ERR_MSG_CREATE_WINDOW_EX "'CreateWindowEx' Failed"
#define ERR_MSG_DESTORY_WINDOW "'DestroyWindow' Failed!"
#define ERR_MSG_GET_TEXT_METRICS "'GetTextMetrics' Failed!"
#define ERR_MSG_DESTROY_CARET "'DestroyCaret' Failed!"
#define ERR_MSG_CREATE_CARET "'CreateCaret' Failed!"
#define ERR_MSG_SHOW_CARET "'ShowCaret' Failed!"
#define ERR_MSG_HIDE_CARET "'HideCaret' Failed!"
#define ERR_MSG_SET_CARET_POS "'SetCaretPos' Failed!"
#define ERR_MSG_SET_FOCUS "'SetFocus' Failed!"
#define ERR_MSG_SELECT_OBJECT_HFONT "'SelectObject' Failed - HFONT!"
#define ERR_MSG_DELETE_OBJECT "'DeleteObject' Failed"
#define ERR_MSG_DELETE_OBJECT_HFONT "'DeleteObject' Failed - HFONT!"
#define ERR_MSG_OPEN_CLIPBOARD "'OpenClipboard' Failed!"
#define ERR_MSG_EMTY_CLIPBOARD "'EmptyClipboard' Failed!"
#define ERR_MSG_SET_CLIPBOARD_DATA "'SetClipboardData' Failed!"
#define ERR_MSG_GET_CLIPBOARD_DATA "'GetClipboardData' Failed!"
#define ERR_MSG_CLOSE_CLIPBOARD "'CloseClipboard' Failed!"
#define ERR_MSG_GLOBAL_ALLOC "'GlobalAlloc' Failed!"
#define ERR_MSG_GLOBAL_UNLOCK "'GlobalUnlock' Failed!"
#define ERR_MSG_GLOBAL_LOCK "'GlobalLock' Failed!"
#define ERR_MSG_CREATE_SOLID_BRUSH "'CreateSolidBrush' Failed!"
#define ERR_MSG_FREE_CONSOLE "'FreeConsole' Failed!"
#define ERR_MSG_ALLOC_CONSOLE  "'AllocConsole' Failed!"
#define ERR_MSG_STRECH_BLT "'StretchBlt' Failed!"
#define ERR_MSG_DELETE_DC "'DeleteDC' Failed!"
